apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kuber
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        name: network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
           limits:
             cpu: 200m
             memory: 512Mi
           requests:
             cpu: 100m
             memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-3r-nginx-multitool
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: tool
      protocol: TCP
      port: 9002
      targetPort: 8080
  selector:
    app: main