---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.0
        ports:
        - containerPort: 80
        resources:
           limits:
             cpu: 200m
             memory: 512Mi
           requests:
             cpu: 50m
             memory: 128Mi
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        name: network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
           limits:
             cpu: 20m
             memory: 128Mi
           requests:
             cpu: 10m
             memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: main