---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.77.218
      ansible_user: centos
vector:
  hosts:
    vector-01:
      ansible_host: 192.168.77.218
      ansible_user: centos
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 192.168.77.218
      ansible_user: centos
