node("linux"){
    stage("Git checkout"){
        git credentialsId: '63c56f20-edcd-4100-8f8f-1aa14682e79a', url: 'https://github.com/aragastmatb/example-playbook.git'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    stage("Run playbook"){
        if (secret_check){
            sh 'ansible-playbook site.yml -i inventory/prod.yml -e "ansible_become_password=p@$$w0rd"'
        }
        else{
            echo 'need more action'
        }

    }
}
