version: '3.8'

volumes:
  db13:

services:
  pgdb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-db
    volumes:
      - db13:/var/lib/postgresql/data
      - /home/vit/bkp:/home/bkp
    ports:
      - ${POSTGRES_PORT:-5432}:5432
