apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: pod
spec:
  containers:
  - name: pod
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
