---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-testuser
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-testuser
  namespace: default
subjects:
- kind: User
  name: testuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-testuser
  apiGroup: rbac.authorization.k8s.io