---
vector_config:
  sources:
      nginx_logs:
        type: file
        include:
          - /var/log/nginx/my_access.log
        read_from: end
  sinks:
    clickhouse:
      type: clickhouse
      inputs:
        - nginx_logs
      database: logs
      endpoint: 'http://{{ hostvars[''clickhouse-01''].ansible_host }}:8123'
      table: vector_logs
      compression: gzip
      skip_unknown_fields: true