version: '3.8'

volumes:
  data:
  bkp:

services:
  pgdb:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=test-admin-user
      - POSTGRES_DB=test-db
    volumes:
      - data:/var/lib/postgresql/data
#      - /home/vit/bkp:/home/bkp
      - bkp:/home/bkp
    ports:
      - ${POSTGRES_PORT:-5432}:5432
